/**
 * Data Export Utilities
 * 
 * Functions to export user data in various formats.
 */

export interface ExportableData {
  user: {
    address: string;
    joinedAt: string;
  };
  statistics: Record<string, string | number>;
  circles: {
    name: string;
    role: string;
    status: string;
    contribution?: number;
  }[];
  badges: {
    name: string;
    earnedAt: string;
  }[];
  activity: {
    type: string;
    description: string;
    date: string;
    amount?: number;
  }[];
}

/**
 * Export data as JSON file
 */
export function exportAsJSON(data: ExportableData, filename = 'stacksusu-profile'): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  downloadBlob(blob, `${filename}.json`);
}

/**
 * Export data as CSV file
 */
export function exportAsCSV(data: ExportableData, filename = 'stacksusu-profile'): void {
  const lines: string[] = [];
  
  // User info
  lines.push('=== User Information ===');
  lines.push('Address,Joined At');
  lines.push(`"${data.user.address}","${data.user.joinedAt}"`);
  lines.push('');
  
  // Statistics
  lines.push('=== Statistics ===');
  lines.push('Metric,Value');
  for (const [key, value] of Object.entries(data.statistics)) {
    lines.push(`"${formatKey(key)}","${value}"`);
  }
  lines.push('');
  
  // Circles
  if (data.circles.length > 0) {
    lines.push('=== Circles ===');
    lines.push('Name,Role,Status,Contribution');
    for (const circle of data.circles) {
      lines.push(`"${circle.name}","${circle.role}","${circle.status}","${circle.contribution || 'N/A'}"`);
    }
    lines.push('');
  }
  
  // Badges
  if (data.badges.length > 0) {
    lines.push('=== NFT Badges ===');
    lines.push('Name,Earned At');
    for (const badge of data.badges) {
      lines.push(`"${badge.name}","${badge.earnedAt}"`);
    }
    lines.push('');
  }
  
  // Activity
  if (data.activity.length > 0) {
    lines.push('=== Activity History ===');
    lines.push('Type,Description,Date,Amount');
    for (const item of data.activity) {
      lines.push(`"${item.type}","${item.description}","${item.date}","${item.amount || 'N/A'}"`);
    }
  }
  
  const csv = lines.join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${filename}.csv`);
}

/**
 * Generate a printable HTML report
 */
export function exportAsHTML(data: ExportableData, filename = 'stacksusu-profile'): void {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StackSUSU Profile Export</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { color: #6366f1; }
    h2 { color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; margin-top: 2rem; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid #e2e8f0; }
    th { background: #f8fafc; font-weight: 600; }
    .badge { display: inline-block; padding: 0.25rem 0.5rem; background: #dbeafe; color: #1e40af; border-radius: 0.25rem; font-size: 0.875rem; }
    .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>🔄 StackSUSU Profile Report</h1>
  <p><strong>Address:</strong> ${data.user.address}</p>
  <p><strong>Member since:</strong> ${data.user.joinedAt}</p>
  <p><strong>Exported:</strong> ${new Date().toLocaleString()}</p>
  
  <h2>📊 Statistics</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    ${Object.entries(data.statistics).map(([k, v]) => `<tr><td>${formatKey(k)}</td><td>${v}</td></tr>`).join('')}
  </table>
  
  ${data.circles.length > 0 ? `
  <h2>⭕ Circles</h2>
  <table>
    <tr><th>Name</th><th>Role</th><th>Status</th><th>Contribution</th></tr>
    ${data.circles.map(c => `<tr><td>${c.name}</td><td>${c.role}</td><td>${c.status}</td><td>${c.contribution || 'N/A'}</td></tr>`).join('')}
  </table>
  ` : ''}
  
  ${data.badges.length > 0 ? `
  <h2>🏆 NFT Badges</h2>
  <div>
    ${data.badges.map(b => `<span class="badge">${b.name}</span>`).join(' ')}
  </div>
  ` : ''}
  
  <div class="footer">
    <p>Generated by StackSUSU - Decentralized Savings Circles</p>
  </div>
</body>
</html>
`.trim();

  const blob = new Blob([html], { type: 'text/html' });
  downloadBlob(blob, `${filename}.html`);
}

/**
 * Download a Blob as a file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Convert camelCase to Title Case
 */
function formatKey(key: string): string {
  return key
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, str => str.toUpperCase())
    .trim();
}
